mutation CreateSingleCamJob($takeId: String!, $metadata: AWSJSON!, $options: OptionsInput) {
    job: createSingleCamJob(takeId: $takeId, metadata: $metadata, options: $options) {
        id
        state
    }
}

query Job($jobId: ID!) {
    job: getJob(jobId: $jobId) {
        state
        outputs {
            key
            file {
                id
                presignedUrl
            }
        }
    }
}

query Thing{
  __type(name: "MocapModelOptionsInput") {
    enumValues {
      name
    }
  }
}
