# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v

  unittest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build for iOS
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MoveSingleAPISwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" | xcpretty
    - name: Run iOS tests
      run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MoveSingleAPISwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 14" | xcpretty
