# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v

  unittest:
    runs-on: macos-latest
    steps:
    - name: Switch xcode to latest
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Double-check macOS version
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list
    - uses: mxcl/xcodebuild@v2
      with:
        platform: iOS
        scheme: MoveSingleAPISwift
        action: test
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
